server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/countries {
    rewrite ^/api/countries(.*)$ /countries/v5$1 break;

    proxy_pass https://api.restcountries.com;
    proxy_ssl_server_name on;
    proxy_set_header Host api.restcountries.com;
    proxy_set_header Authorization "Bearer ${REST_COUNTRIES_API_KEY}";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
